# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60030cfc014a0e954ded89a23502dadb4d68173dad106296877779bdfe711adcdb4d53b8fa8ffc1474e2f0c13ba6d9a7b5d3c5c910b384c4553b6d6f3c0b077

test:
  secret_key_base: 29e35c2319f3e74f39f7718d8e9c18fc6256907d1ba5f6d6c188b460cd47fc1c5c818e9eff13c8b6f70c301791f68d8a8761457073e8557051bc0a99a057408c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
